/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
///.Function.begin.param.object.type:Class.CompressedSA
///.Function.begin.class:Class.CompressedSA
///.Function.end.param.object.type:Class.CompressedSA
///.Function.end.class:Class.CompressedSA
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
///.Function.RankDictionary#getFibre.param.fibreTag.type:Spec.SequenceBitMask Fibres
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
///.Metafunction.Fibre.param.TContainer.type:Class.RankDictionary
///.Metafunction.Fibre.param.TSpec.type:Tag.WaveletTree Fibres
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
///.Metafunction.Fibre.param.TContainer.type:Class.RightArrayBinaryTree
///.Metafunction.Fibre.param.TSpec.type:Tag.RightArrayBinaryTree Fibres
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
///.Function.begin.param.object.type:Class.RightArrayBinaryTree
///.Function.begin.class:Spec.RightArrayBinaryTree Iterator
///.Function.container.param.iterator.type:Class.RightArrayBinaryTree
///.Function.container.class:Spec.RightArrayBinaryTree Iterator
///.Function.end.param.object.type:Class.RightArrayBinaryTree
///.Function.end.class:Spec.RightArrayBinaryTree Iterator
///.Function.goDown.param.iterator.type:Spec.RightArrayBinaryTree Iterator
///.Function.goDown.class:Spec.RightArrayBinaryTree Iterator
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
///.Metafunction.Fibre.param.TSpec.type:Tag.SentinelRankDictionary Fibres
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
/*_DDDOC_PLACEHOLDER*/
///.Function.clear.param.object.type:Class.SparseString
///.Function.clear.class:Class.SparseString
///.Function.empty.param.object.type:Class.SparseString
///.Function.empty.class:Class.SparseString
///.Function.assignValue.param.container.type:Class.SparseString
///.Function.assignValue.class:Class.SparseString
///.Function.getValue.param.container.type:Class.SparseString
///.Function.getValue.class:Class.SparseString
///.Function.value.param.container.type:Class.SparseString
///.Function.value.class:Class.SparseString
///.Function.length.param.object.type:Class.SparseString
///.Function.length.class:Class.SparseString
///.Function.resize.param.object.type:Class.SparseString
///.Function.resize.class:Class.SparseString
///.Spec.VSTree Iterator.param.TContainer.type:Spec.FMIndex
///.Function.begin.param.object.type:Spec.FMIndex
