                              Mason Materializer
                         Methylation Level Simulator

                      http://www.seqan.de/projects/mason
                              Version 2.0.0-beta1
                                February, 2014

                               Manuel Holtgrewe

------------------------------------------------------------------------------
Table of Contents
------------------------------------------------------------------------------

  1. Overview
  2. Examples
  3. Reference and Contact

------------------------------------------------------------------------------
1. Overview
------------------------------------------------------------------------------

Mason Materializer takes a reference FASTA file and a VCF variant file and
applies the variants to the reference.  The input VCF can contain all variants
that can be generated by the mason_variator program.

This functionality is useful if you want to look at the actual sequence of a
personalized genome, for example, or when applying the variants from a
previously simulated VCF file to put it into an external read simulator.

------------------------------------------------------------------------------
2. Examples
------------------------------------------------------------------------------

You can find the binary "mason_materializer" in the directory "bin" and the
example file in the directory "examples".

------------------------------------------------------------------------------
2.1 Help
------------------------------------------------------------------------------

The command:

  $ mason_materializer --help

prints the help for Mason Materializer.

------------------------------------------------------------------------------
2.2 Materializing a VCF file.
------------------------------------------------------------------------------

We take the files adeno_virus.fa and apply the VCF file adeno_virus.vcf to it.
We write the resulting FASTA file to adeno_out.fa

  $ adeno_materializer -ir adeno_virus.fa -iv adeno_virus.vcf -o adeno_out.fa
  ...
  $ head adeno_out.fa
  >gi|56160436|ref|AC_000005.1|/1
  CCTATCTAATAATTTACCTTATACTGGACTAGTGCCAATATTAAAATGAAGTGGGCGTAGTGTGTAATTT
  GATTGGGTGGAGGTGTGGCTTTGGCGTGCTTGTAAGTTTGGGCGGATGAGGAAGTGGGGCGCGGCGTGGG
  AGCCGGGCGCGCCGGATGTGACGTTTTAGACGCCATTTTACACGGAAATGATGTTTTTTGGGCGTTGTTT
  GTGCAAATTTTGTGTTTTAGGCGCGAAAACTGAAATGCGGAAGTGAAAATTGATGACGGCAATTTTATTA
  TAGGCGCGGAATATTTACCGAGGGCAGAGTGAACTCTGAGCCTCTACGTGTGGGTTTCGATACGTGAGCG
  ACGGGGAAACTCCACGTTGGCGCTCAAAGGGCGCGTTTATTGTTCTGTCAGCTGATCGTTTGGGTATTTA
  ATGCCGCCGTGTTCGTCAAGAGGCCACTCTTGAGTGCCAGCGAGAAGAGTTTTCTCTGCCAGCTCATTTT
  CACGGCGCCATTATGAGAACTGAAATGACTCCCTTGGTCCTGTCGTATCAGGAAGCTGACGACATATTGG
  AGCATTTGGTGGACAACTTTTTTAACGAGGTACCCAGTGATGATGATCTTTATGTTCCGTCTCTTTACGA
  $ grep '^>gi' adeno_out.fa
  >gi|56160436|ref|AC_000005.1|/1

Note that there is only one haplotype described in the VCF file.
mason_materializer generates a haplotype into the output FASTA file for each
haplotype in the VCF and sequence in the reference file.  The name of the
haplotype is the reference name with a suffix consisting of a dash and the
number of the haplotype.

------------------------------------------------------------------------------
3. Reference and Contact
------------------------------------------------------------------------------

In case of questions and problems please contact the mailing list

  https://lists.fu-berlin.de/listinfo/seqan-dev

or file a bug at

  http://trac.seqan.de/newticket

