#ifndef SEQAN_EXTRAS_APPS_NGS_ROI_VERSION_H_
#define SEQAN_EXTRAS_APPS_NGS_ROI_VERSION_H_

#define VERSION "0.2.1"
#define DATE    "October 2013"

#endif  // #ifndef SEQAN_EXTRAS_APPS_NGS_ROI_VERSION_H_
